### ISSUE TITLE
Can't connect to Local OPC DA Server(Matrikon.Simulator)

### ISSUE THREAD

**Issue by eduardodinizf** [netsmarttech/node-red-contrib-opc-da#5]
Can't get the credentials to work. My best shot lead me to this error:

![image](https://user-images.githubusercontent.com/26725258/68629065-3ace0180-04c1-11ea-929f-87cc770eae43.png)

I can monitor the server, the tags and everything else via OPC Expert, everything works fine, but I can't connect.

**Comment by dmakarenko-connyun** [comment]
I have the same issue. MatriconOPC Explorer shows that everything is running but I cannot connect to the server.

**Comment by steuck13** [comment]
Greetings,
This problem usually appear when permissions for remote launch and access are not corretcly configured and/or when authentication level is not set to "Connect". I'll try to simulate a w10 environment, maybe it's something we missed.
Ty

**Comment by steuck13** [comment]
Greetings,
I was able to communicate successfully with the Matrikon OPC Server (running on a w10 machine) but besides the default DCOM configuration and security options enabled during install I also had to disable my Firewall.
If everything was correctly configured I suggest you check your firewall.

[]'s

**Comment by eduardodinizf** [comment]
Thank you, I will try that. Would you mind sharing how you configurated the OPC DA IN node connection with Matrikon OPC Server(Domain, User, which password, etc.)?

**Comment by eduardodinizf** [comment]
Got it to work, it was indeed a firewall issue. I'm closing the issue. Thanks @steuck13 .

**Comment by Cat2794** [comment]
Hello @eduardodinizf, 

Could you please tell me how exactly you setup your Matrikon in order for a successful connection? I have left everything on default and I also tried disabling my firewall and I am getting the following error: 
![image](https://user-images.githubusercontent.com/64475801/139587048-f9abb8b5-5980-4a0b-9b1b-ffc4c68e79cf.png)
If you could briefly tell me how did you install the Matrikon Server Simulator and what additional configuration you set or have any helpful link it would be very appreciated

Thank you very much,

**Comment by ErickRAb** [comment]
> Hola@eduardodinizf,
> 
> ¿Podría decirme cómo configura exactamente su Matrikon para una conexión exitosa? Dejé todo por defecto y también intenté deshabilitar mi firewall y recibo el siguiente error: Si pudiera decirme brevemente cómo instaló Matrikon Server Simulator y qué configuración adicional estableció o tiene algún enlace útil, sería muy apreciado ![imagen](https://user-images.githubusercontent.com/64475801/139587048-f9abb8b5-5980-4a0b-9b1b-ffc4c68e79cf.png)
> 
> Muchísimas gracias,

Hello, how are you, I have the same problem, were you able to solve it?

**Comment by papercodeIN** [comment]
> > Hola@eduardodinizf,
> > ¿Podría decirme cómo configura exactamente su Matrikon para una conexión exitosa? Dejé todo por defecto y también intenté deshabilitar mi firewall y recibo el siguiente error: Si pudiera decirme brevemente cómo instaló Matrikon Server Simulator y qué configuración adicional estableció o tiene algún enlace útil, sería muy apreciado ![imagen](https://user-images.githubusercontent.com/64475801/139587048-f9abb8b5-5980-4a0b-9b1b-ffc4c68e79cf.png)
> > Muchísimas gracias,
> 
> Hello, how are you, I have the same problem, were you able to solve it?

Hi Have you manage to solve this problem ? Can someone share screenshot of their configuration ?
