### ISSUE TITLE
OPC Timestamp Format

### ISSUE THREAD

**Issue by tiagoafseixas** [netsmarttech/node-red-contrib-opc-da#6]
When reading data from an OPC server I am getting the timestamp formatted as such:
> timestamp: "Sun, 31 Dec 1600 23:57:55 GMT

On Matrikon Explorer the date is ok.

**Comment by steuck13** [comment]
Greetings, I'll take a look. Probably a problem with one of our libs.
Ty

**Comment by steuck13** [comment]
Would you mind sharing your Node-RED flow with us?
Thx

**Comment by tiagoafseixas** [comment]
Here you go.
[opcda.import.flow.txt](https://github.com/netsmarttech/node-red-contrib-opc-da/files/3906324/opcda.import.flow.txt)

**Comment by steuck13** [comment]
Greetings
The node-opc-da lib was updated. Try updating to the latest version and see if the timestamp problem persists.

[]'s

**Comment by tiagoafseixas** [comment]
Hi,

The problem is now fixed.

Ty
